In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#loading the data
train_data= pd.read_csv('Train.csv')
test_data= pd.read_csv('Test.csv')

In [3]:
#count the number of missing data in the training set
train_data.isna().sum()

Employee_ID                    0
Gender                         0
Age                          412
Education_Level                0
Relationship_Status            0
Hometown                       0
Unit                           0
Decision_skill_possess         0
Time_of_service              144
Time_since_promotion           0
growth_rate                    0
Travel_Rate                    0
Post_Level                     0
Pay_Scale                      9
Compensation_and_Benefits      0
Work_Life_balance             11
VAR1                           0
VAR2                         577
VAR3                           0
VAR4                         656
VAR5                           0
VAR6                           0
VAR7                           0
Attrition_rate                 0
dtype: int64

In [4]:
#count the number of data in the test set
test_data.isna().sum()

Employee_ID                    0
Gender                         0
Age                          161
Education_Level                0
Relationship_Status            0
Hometown                       0
Unit                           0
Decision_skill_possess         0
Time_of_service               52
Time_since_promotion           0
growth_rate                    0
Travel_Rate                    0
Post_Level                     0
Pay_Scale                      3
Compensation_and_Benefits      0
Work_Life_balance              5
VAR1                           0
VAR2                         217
VAR3                           0
VAR4                         298
VAR5                           0
VAR6                           0
VAR7                           0
dtype: int64

In [5]:
#filling all the missing values of the required columns with their mean
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
train_data['Age']= imputer.fit_transform(train_data['Age'].values.reshape(-1,1))
train_data['Time_of_service']= imputer.fit_transform(train_data['Time_of_service'].values.reshape(-1,1))
train_data['Pay_Scale']= imputer.fit_transform(train_data['Pay_Scale'].values.reshape(-1,1))
train_data['VAR2']= imputer.fit_transform(train_data['VAR2'].values.reshape(-1,1))
train_data['VAR4']= imputer.fit_transform(train_data['VAR4'].values.reshape(-1,1))
train_data['Work_Life_balance']= imputer.fit_transform(train_data['Work_Life_balance'].values.reshape(-1,1))
test_data['Age']= imputer.fit_transform(test_data['Age'].values.reshape(-1,1))
test_data['Time_of_service']= imputer.fit_transform(test_data['Time_of_service'].values.reshape(-1,1))
test_data['Pay_Scale']= imputer.fit_transform(test_data['Pay_Scale'].values.reshape(-1,1))
test_data['VAR2']= imputer.fit_transform(test_data['VAR2'].values.reshape(-1,1))
test_data['VAR4']= imputer.fit_transform(test_data['VAR4'].values.reshape(-1,1))
test_data['Work_Life_balance']= imputer.fit_transform(test_data['Work_Life_balance'].values.reshape(-1,1))

In [6]:
#checking if any missing values got left out in the training set
train_data.isna().sum()

Employee_ID                  0
Gender                       0
Age                          0
Education_Level              0
Relationship_Status          0
Hometown                     0
Unit                         0
Decision_skill_possess       0
Time_of_service              0
Time_since_promotion         0
growth_rate                  0
Travel_Rate                  0
Post_Level                   0
Pay_Scale                    0
Compensation_and_Benefits    0
Work_Life_balance            0
VAR1                         0
VAR2                         0
VAR3                         0
VAR4                         0
VAR5                         0
VAR6                         0
VAR7                         0
Attrition_rate               0
dtype: int64

In [7]:
#checking if any missing values got left out in the test set
test_data.isna().sum()

Employee_ID                  0
Gender                       0
Age                          0
Education_Level              0
Relationship_Status          0
Hometown                     0
Unit                         0
Decision_skill_possess       0
Time_of_service              0
Time_since_promotion         0
growth_rate                  0
Travel_Rate                  0
Post_Level                   0
Pay_Scale                    0
Compensation_and_Benefits    0
Work_Life_balance            0
VAR1                         0
VAR2                         0
VAR3                         0
VAR4                         0
VAR5                         0
VAR6                         0
VAR7                         0
dtype: int64

In [8]:
features= ['Age', 'Education_Level', 'Time_of_service', 'Time_since_promotion', 'growth_rate', 'growth_rate', 'Travel_Rate', 'Post_Level', 'Pay_Scale', 'Compensation_and_Benefits' , 'Work_Life_balance']    #selecting the features for predicting attrition value
x_train= train_data[features].values    #storing the training data in a new variable with the required features
y_train= train_data.iloc[:, -1].values   #storing the test data in a new variable with the dependent column
x_test= test_data[features].values    #storing the test data in a new variable with the required features 

In [9]:
print(x_train)

[[42.0 4 4.0 ... 7.0 'type2' 3.0]
 [24.0 3 5.0 ... 6.0 'type2' 4.0]
 [58.0 3 27.0 ... 8.0 'type2' 1.0]
 ...
 [49.0 3 10.0 ... 3.0 'type2' 4.0]
 [47.0 3 24.0 ... 8.0 'type0' 2.0]
 [58.0 3 22.0 ... 5.0 'type2' 3.0]]


In [10]:
print(x_test)

[[32.0 5 7.0 ... 4.0 'type2' 1.0]
 [65.0 2 41.0 ... 1.0 'type2' 1.0]
 [52.0 3 21.0 ... 8.0 'type3' 1.0]
 ...
 [60.0 4 35.0 ... 9.0 'type3' 3.0]
 [51.0 1 23.0 ... 6.0 'type3' 1.0]
 [45.0 1 12.0 ... 8.0 'type4' 4.0]]


In [11]:
#encoding categorical data in training set using One Hot Encoding method 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
x_train = np.array(ct.fit_transform(x_train))

In [12]:
print(x_train)

[[0.0 0.0 1.0 ... 1 7.0 3.0]
 [0.0 0.0 1.0 ... 3 6.0 4.0]
 [0.0 0.0 1.0 ... 2 8.0 1.0]
 ...
 [0.0 0.0 1.0 ... 2 3.0 4.0]
 [1.0 0.0 0.0 ... 5 8.0 2.0]
 [0.0 0.0 1.0 ... 4 5.0 3.0]]


In [13]:
#encoding categorical data in test set using One Hot Encoding method 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
x_test = np.array(ct.fit_transform(x_test))

In [14]:
print(x_test)

[[0.0 0.0 1.0 ... 5 4.0 1.0]
 [0.0 0.0 1.0 ... 1 1.0 1.0]
 [0.0 0.0 0.0 ... 1 8.0 1.0]
 ...
 [0.0 0.0 0.0 ... 2 9.0 3.0]
 [0.0 0.0 0.0 ... 2 6.0 1.0]
 [0.0 0.0 0.0 ... 2 8.0 4.0]]


In [15]:
#training of x_train and y_train using Multiple Linear Regression
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
#predicting the attrition value using the test set
y_pred = regressor.predict(x_test)

In [17]:
#saving my results in a .csv file
output = pd.DataFrame({'Employee_ID': test_data.Employee_ID, 'Attrition_rate': y_pred})
output.to_csv('my_prediction.csv', index=False)